#### PRML lab-1<br>Numpy


### Roll:CS22B2020  <br>                     Name : G.Sriram

In [1]:
import numpy as np

i) Array Creation and Basic Operations <br>
a) Create a 1D array of numbers from 0 to 19 using np.arange(). <br>
b) Reshape this array into a 4x5 2D array.<br>
 c) Create a 3x3 array of all zeros, and another 3x3 array of all ones. <br>
d) Generate a 1D array of 10 evenly spaced numbers between 1 and 100 using np.linspace().


In [2]:
# Question -1
# i)
oneD_array = np.arange(0,20)
oneD_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [4]:
oneD_array = oneD_array.reshape(4,5)
oneD_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [5]:
oneD_array.shape

(4, 5)

In [6]:
zeros = np.zeros((3,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
ones = np.ones((3,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

ii) Indexing, Slicing, and Iterating <br>
a) From the 4x5 array created in 1b, extract the following:<br>
The element at position (2,3)<br>
The second row<br>
The last column<br>
b) Reverse the order of elements in the second row.<br> 
      c) Create a 3x3 array with random integers between 1 and 100, then find          all elements greater than 50.<br>



In [13]:
# ii)
oneD_array[2][3]

13

In [14]:
oneD_array[1]

array([5, 6, 7, 8, 9])

In [16]:
oneD_array[:,-1]

array([ 4,  9, 14, 19])

In [17]:
oneD_array[1,:][::-1]

array([9, 8, 7, 6, 5])

In [27]:
array = np.random.randint(1,100,30)
array

array([34, 92, 15, 96, 62, 39, 67, 27, 57, 96, 47, 18, 50, 93, 16, 81, 75,
       66, 79, 33, 61, 60, 70, 67, 41, 19, 26, 28, 58, 45])

In [28]:
array[array>50]

array([92, 96, 62, 67, 57, 96, 93, 81, 75, 66, 79, 61, 60, 70, 67, 58])

iii) Conditional Statements and Boolean Operations <br>a) Create a 5x5 array of random integers between 0 and 100. <br>b) Create a boolean mask for elements between 30 and 70 (inclusive). <br>c) Use this mask to replace all elements outside this range with the value -1.<br>


In [14]:
random_arr = np.random.randint(0,100,(5,5))
random_arr

array([[73, 46, 39, 85, 24],
       [14, 96, 62, 79, 86],
       [20, 27, 58, 41, 88],
       [59, 66, 64, 76, 60],
       [84, 42, 99, 33,  2]])

In [15]:
random_arr_bool = (random_arr<70) & (random_arr>30)
random_arr[random_arr_bool]

array([46, 39, 62, 58, 41, 59, 66, 64, 60, 42, 33])

In [16]:
random_arr[random_arr_bool] = -1
random_arr

array([[73, -1, -1, 85, 24],
       [14, 96, -1, 79, 86],
       [20, 27, -1, -1, 88],
       [-1, -1, -1, 76, -1],
       [84, -1, 99, -1,  2]])

iv) Basic Mathematical Operations <br>
a) Create two 3x3 arrays with random integers between 1 and 10. <br>
b) Perform element-wise addition, subtraction, multiplication, and division on these arrays. <br>
c) Calculate the dot product of these two arrays.
<br>

In [6]:
arr1 = np.random.randint(1,10,(3,3))
arr1

array([[6, 2, 8],
       [7, 7, 8],
       [5, 7, 6]])

In [7]:
arr2 = np.random.randint(1,10,(3,3))
arr2

array([[9, 7, 7],
       [7, 4, 6],
       [9, 4, 5]])

In [8]:
arr1 + arr2

array([[15,  9, 15],
       [14, 11, 14],
       [14, 11, 11]])

In [9]:
arr1 - arr2

array([[-3, -5,  1],
       [ 0,  3,  2],
       [-4,  3,  1]])

In [10]:
arr1 * arr2

array([[54, 14, 56],
       [49, 28, 48],
       [45, 28, 30]])

In [11]:
arr1 / arr2

array([[0.66666667, 0.28571429, 1.14285714],
       [1.        , 1.75      , 1.33333333],
       [0.55555556, 1.75      , 1.2       ]])

In [12]:
np.dot(arr1,arr2)

array([[140,  82,  94],
       [184, 109, 131],
       [148,  87, 107]])

v) Universal Functions<br> a) Using the array from task 3a, calculate:<br>
The mean of the entire array<br>
The standard deviation of each row<br>
The variance of each column<br>
The median of the entire array<br>
The minimum and maximum values of each row<br>


In [18]:
random_arr = np.random.randint(0,100,(5,5))
random_arr

array([[61, 73, 73, 94, 92],
       [98, 68, 36, 20, 33],
       [38, 48, 77, 33, 36],
       [10, 86, 20, 13,  3],
       [75, 36, 28, 38, 17]])

In [19]:
random_arr.mean()

48.24

In [20]:
random_arr.std(axis=1)

array([12.56343902, 28.31254139, 16.10714127, 30.29587431, 19.54891301])

In [58]:
random_arr.var(axis=0)

array([800.24, 112.24, 610.4 , 271.6 , 467.84])

In [59]:
np.median(random_arr)

47.0

In [62]:
np.min(random_arr,axis=0) #col

array([24, 32, 35,  4, 23])

In [63]:
np.min(random_arr,axis=1) #row

array([ 4, 31,  7, 32, 28])

In [64]:
np.max(random_arr,axis=0) #col

array([98, 61, 99, 44, 81])

In [65]:
np.min(random_arr,axis=1) #row

array([ 4, 31,  7, 32, 28])

vi) Shape Manipulation <br>
a) Create a 1D array of 24 random integers between 0 and 100.<br>
 b) Reshape this array into a 4x6 2D array. <br>
c) Flatten this 2D array back to 1D. <br>
d) Transpose the 2D array. <br>
e) Stack two 3x3 arrays vertically, then stack the result with another 3x3 array horizontally.


In [66]:
Random_arr = np.random.randint(0,100,24)

In [67]:
Random_arr

array([88, 50, 57, 19, 32,  2, 46, 22, 93, 75, 72, 59, 39, 38, 93, 31, 22,
       51, 34,  0, 63, 49, 41, 99])

In [68]:
Random_arr_2d= Random_arr.reshape(4,6)
Random_arr_2d

array([[88, 50, 57, 19, 32,  2],
       [46, 22, 93, 75, 72, 59],
       [39, 38, 93, 31, 22, 51],
       [34,  0, 63, 49, 41, 99]])

In [69]:
Random_arr = Random_arr.reshape(-1,)

Random_arr

array([88, 50, 57, 19, 32,  2, 46, 22, 93, 75, 72, 59, 39, 38, 93, 31, 22,
       51, 34,  0, 63, 49, 41, 99])

In [70]:
Tran = Random_arr_2d.T
Tran

array([[88, 46, 39, 34],
       [50, 22, 38,  0],
       [57, 93, 93, 63],
       [19, 75, 31, 49],
       [32, 72, 22, 41],
       [ 2, 59, 51, 99]])

In [71]:
Arr1 = np.random.randint(1,50,(3,3))
Arr2 = np.random.randint(1,50,(3,3))
print(Arr1)
print(Arr2)

[[18 46 42]
 [29  4 23]
 [22 19  8]]
[[ 4 43 14]
 [40 31 43]
 [ 9 40 27]]


In [72]:
Vstack = np.vstack((Arr1,Arr2))
Vstack

array([[18, 46, 42],
       [29,  4, 23],
       [22, 19,  8],
       [ 4, 43, 14],
       [40, 31, 43],
       [ 9, 40, 27]])

In [73]:
Hstack = np.hstack((Vstack,Vstack))
Hstack

array([[18, 46, 42, 18, 46, 42],
       [29,  4, 23, 29,  4, 23],
       [22, 19,  8, 22, 19,  8],
       [ 4, 43, 14,  4, 43, 14],
       [40, 31, 43, 40, 31, 43],
       [ 9, 40, 27,  9, 40, 27]])

vii) Copy Methods <br>
a) Create a 3x3 array of random integers. <br>
b) Create three copies of this array using direct assignment, view(), and copy().<br> c) Modify an element in each copy and explain the differences in how the original array is affected.


In [74]:
Random_intarr = np.random.randint(1,50,(3,3))
Random_intarr

array([[25, 24, 30],
       [25,  4, 31],
       [29,  9, 24]])

In [75]:
Copy1 = Random_intarr
Copy2 = Random_intarr.view()
Copy3 = Random_intarr.copy()
print(Copy1)
print(Copy2)
print(Copy3)

[[25 24 30]
 [25  4 31]
 [29  9 24]]
[[25 24 30]
 [25  4 31]
 [29  9 24]]
[[25 24 30]
 [25  4 31]
 [29  9 24]]


In [76]:
Copy1[0,0] = 100
Copy2[0,0] = 200
Copy3[0,0] = 300

In [77]:
print("Original Array :",Random_intarr)
print("Copy1 : ",Copy1)
print("Copy2 : ",Copy2)
print("Copy3 : ",Copy3)

Original Array : [[200  24  30]
 [ 25   4  31]
 [ 29   9  24]]
Copy1 :  [[200  24  30]
 [ 25   4  31]
 [ 29   9  24]]
Copy2 :  [[200  24  30]
 [ 25   4  31]
 [ 29   9  24]]
Copy3 :  [[300  24  30]
 [ 25   4  31]
 [ 29   9  24]]


Explanation:Direct Assignment (arr_assigned):This just creates a new reference to the same array. Any modifications made to arr_assigned will directly affect the original array since they both point to the same memory location.View (arr_view):A view() creates a shallow copy of the array. Changes made to this view will reflect in the original array because it shares the same data buffer. However, the view itself is a separate object, so it can have a different shape or stride, but the data is shared.Copy (arr_copy):A copy() creates a deep copy of the array. This means it creates an entirely new array in memory, and modifications to this new array do not affect the original array.

viii) Handling NULL Values<br>
 a) Create a 4x4 array of random floats between 0 and 1.<br> 
b) Replace some values with NaN (Not a Number). <br>
c) Use np.isnan() to create a boolean mask identifying the NaN values. <br>
d) Calculate the mean of the array, ignoring the NaN values.


In [78]:
Rand_float = np.random.rand(4,4)
Rand_float

array([[0.85791899, 0.96200303, 0.40431864, 0.01879566],
       [0.60954407, 0.99990965, 0.3282568 , 0.2448239 ],
       [0.38523431, 0.73303267, 0.95016665, 0.00111528],
       [0.93063452, 0.70896823, 0.48005814, 0.4855251 ]])

In [79]:
Rand_float[0,1] = np.nan
Rand_float[0,2] = np.nan
Rand_float[1,1] = np.nan
Rand_float[2,0] = np.nan
Rand_float

array([[0.85791899,        nan,        nan, 0.01879566],
       [0.60954407,        nan, 0.3282568 , 0.2448239 ],
       [       nan, 0.73303267, 0.95016665, 0.00111528],
       [0.93063452, 0.70896823, 0.48005814, 0.4855251 ]])

In [80]:
Mask = np.isnan(Rand_float)
Mask

array([[False,  True,  True, False],
       [False,  True, False, False],
       [ True, False, False, False],
       [False, False, False, False]])

In [81]:
Mean = np.nanmean(Rand_float)
Mean

0.5290700011279178

ix) Advanced Challenge<br>
 a) Create a 10x10 array of random integers between 1 and 100. <br>
b) Find the indices of the 5 largest values in the entire array.<br>
 c) Calculate the running average along each row (hint: look into np.cumsum()).<br>
 d) Normalize each column of the array so that it sums to 1.


In [82]:
Rand_arr_int = np.random.randint(1,100,(10,10))
Rand_arr_int

array([[32, 56,  5, 84, 63, 24, 54, 73, 59, 67],
       [95, 64, 60, 40, 63, 65, 99, 60, 36, 25],
       [95, 13, 92, 61, 56, 66, 44, 60, 68, 22],
       [93, 66, 89, 56, 33, 23, 39, 52, 71, 68],
       [55,  5, 25, 81, 41, 31, 58, 89, 40, 69],
       [35,  2, 46, 33, 23, 27, 67, 29,  9, 87],
       [51, 53, 12,  2, 66, 28, 24, 40, 23, 10],
       [23, 49, 27, 88, 67, 45, 16, 85, 82, 85],
       [ 6, 14, 15, 87, 66, 23, 64, 24, 58, 54],
       [17,  7, 65, 56, 35, 14, 37, 79, 24, 13]])

In [84]:
flat_array = Rand_arr_int.flatten()
sorted_indices = np.argsort(flat_array)[-5:]  # Get the last 5 indices of the sorted array (largest values)
largest_indices = np.unravel_index(sorted_indices, Rand_arr_int.shape)  # Convert back to 2D indices
print("\nIndices of the 5 largest values in the array (row, column):\n", list(zip(largest_indices[0], largest_indices[1])))


Indices of the 5 largest values in the array (row, column):
 [(2, 2), (3, 0), (1, 0), (2, 0), (1, 6)]


In [87]:
running_avg = np.cumsum(Rand_arr_int, axis=1) / np.arange(1, Rand_arr_int.shape[1] + 1)
running_avg

array([[32.        , 44.        , 31.        , 44.25      , 48.        ,
        44.        , 45.42857143, 48.875     , 50.        , 51.7       ],
       [95.        , 79.5       , 73.        , 64.75      , 64.4       ,
        64.5       , 69.42857143, 68.25      , 64.66666667, 60.7       ],
       [95.        , 54.        , 66.66666667, 65.25      , 63.4       ,
        63.83333333, 61.        , 60.875     , 61.66666667, 57.7       ],
       [93.        , 79.5       , 82.66666667, 76.        , 67.4       ,
        60.        , 57.        , 56.375     , 58.        , 59.        ],
       [55.        , 30.        , 28.33333333, 41.5       , 41.4       ,
        39.66666667, 42.28571429, 48.125     , 47.22222222, 49.4       ],
       [35.        , 18.5       , 27.66666667, 29.        , 27.8       ,
        27.66666667, 33.28571429, 32.75      , 30.11111111, 35.8       ],
       [51.        , 52.        , 38.66666667, 29.5       , 36.8       ,
        35.33333333, 33.71428571, 34.5       

In [88]:
column_sums = np.sum(array, axis=0)
normalized_array = array / column_sums  # Broadcasting to normalize each column
print("\nColumn-Normalized Array (each column sums to 1):\n", normalized_array)



Column-Normalized Array (each column sums to 1):
 [0.0210136  0.05686032 0.0092707  0.05933251 0.03831891 0.02410383
 0.04140915 0.01668727 0.03522868 0.05933251 0.02904821 0.01112485
 0.03090235 0.05747837 0.00988875 0.0500618  0.04635352 0.0407911
 0.04882571 0.02039555 0.03770087 0.03708282 0.04326329 0.04140915
 0.02533993 0.01174289 0.01606922 0.01730532 0.03584672 0.02781211]


: 


 Question 2<br>
Write a python program to perform matrix operations on an M x N matrix and solve a system of linear equations. Use inbuilt functions to implement the operations. Get two matrices from the user. The program should support the following Menus,
<br><br>
Matrix Addition<br>
Matrix Subtraction<br>
Scalar Matrix Multiplication<br>
Elementwise Matrix <br>
Matrix Multiplication<br>
Matrix Transpose<br>
Trace of a Matrix<br>
Solve System of Linear Equations<br>
Determinant<br>
 Inverse<br>
 Eigen Value and Eigen Vector<br>
 Exit


In [24]:
import numpy as np

# Function to input matrix
def input_matrix(rows, cols):
    print(f"Enter the values for a {rows}x{cols} matrix:")
    matrix = []
    for i in range(rows):
        row = list(map(float, input(f"Enter values for row {i + 1} separated by space: ").split()))
        if len(row) != cols:
            raise ValueError("Number of columns entered doesn't match the expected column size.")
        matrix.append(row)
    return np.array(matrix)

# Function to display menu
def display_menu():
    print("\n--- Matrix Operations Menu ---")
    print("1. Matrix Addition")
    print("2. Matrix Subtraction")
    print("3. Scalar Matrix Multiplication")
    print("4. Element-wise Matrix Multiplication")
    print("5. Matrix Multiplication")
    print("6. Matrix Transpose")
    print("7. Trace of a Matrix")
    print("8. Solve System of Linear Equations")
    print("9. Determinant")
    print("10. Inverse")
    print("11. Eigenvalue and Eigenvector")
    print("12. Exit")

# Start interaction
rows = int(input("Enter the number of rows for Matrix A: "))
cols = int(input("Enter the number of columns for Matrix A: "))
matrix_a = input_matrix(rows, cols)

while True:
    display_menu()
    choice = int(input("Enter your choice (1-12): "))
    
    if choice == 1 or choice == 2 or choice == 4 or choice == 5:  # Operations requiring two matrices
        rows_b = int(input("Enter the number of rows for Matrix B: "))
        cols_b = int(input("Enter the number of columns for Matrix B: "))
        matrix_b = input_matrix(rows_b, cols_b)
        
        if choice == 1:
            # Matrix Addition
            if matrix_a.shape == matrix_b.shape:
                result = matrix_a + matrix_b
                print("Matrix Addition Result:\n", result)
            else:
                print("Error: Matrices must have the same dimensions.")
                
        elif choice == 2:
            # Matrix Subtraction
            if matrix_a.shape == matrix_b.shape:
                result = matrix_a - matrix_b
                print("Matrix Subtraction Result:\n", result)
            else:
                print("Error: Matrices must have the same dimensions.")
                
        elif choice == 4:
            # Element-wise Multiplication
            if matrix_a.shape == matrix_b.shape:
                result = matrix_a * matrix_b
                print("Element-wise Multiplication Result:\n", result)
            else:
                print("Error: Matrices must have the same dimensions.")
                
        elif choice == 5:
            # Matrix Multiplication
            if matrix_a.shape[1] == matrix_b.shape[0]:
                result = np.dot(matrix_a, matrix_b)
                print("Matrix Multiplication Result:\n", result)
            else:
                print("Error: Number of columns of Matrix A must equal the number of rows of Matrix B.")
                
    elif choice == 3:
        # Scalar Matrix Multiplication
        scalar = float(input("Enter the scalar value: "))
        result = matrix_a * scalar
        print(f"Scalar Matrix Multiplication Result (Scalar = {scalar}):\n", result)
        
    elif choice == 6:
        # Matrix Transpose
        result = np.transpose(matrix_a)
        print("Matrix Transpose Result:\n", result)
        
    elif choice == 7:
        # Trace of a Matrix
        if matrix_a.shape[0] == matrix_a.shape[1]:
            result = np.trace(matrix_a)
            print("Trace of Matrix A:", result)
        else:
            print("Error: Matrix must be square.")
            
    elif choice == 8:
        # Solve System of Linear Equations
        print("Enter the constants vector (b) for Ax = b system:")
        const_vector = input_matrix(rows, 1)
        try:
            result = np.linalg.solve(matrix_a, const_vector)
            print("Solution to the system of linear equations:\n", result)
        except np.linalg.LinAlgError as e:
            print("Error:", e)
            
    elif choice == 9:
        # Determinant
        if matrix_a.shape[0] == matrix_a.shape[1]:
            result = np.linalg.det(matrix_a)
            print("Determinant of Matrix A:", result)
        else:
            print("Error: Matrix must be square.")
            
    elif choice == 10:
        # Inverse
        if matrix_a.shape[0] == matrix_a.shape[1]:
            try:
                result = np.linalg.inv(matrix_a)
                print("Inverse of Matrix A:\n", result)
            except np.linalg.LinAlgError as e:
                print("Error:", e)
        else:
            print("Error: Matrix must be square.")
            
    elif choice == 11:
        # Eigenvalue and Eigenvector
        if matrix_a.shape[0] == matrix_a.shape[1]:
            eigenvalues, eigenvectors = np.linalg.eig(matrix_a)
            print("Eigenvalues:\n", eigenvalues)
            print("Eigenvectors:\n", eigenvectors)
        else:
            print("Error: Matrix must be square.")
            
    elif choice == 12:
        # Exit
        print("Exiting the program.")
        break
    
    else:
        print("Invalid choice. Please try again.")


Enter the values for a 2x2 matrix:

--- Matrix Operations Menu ---
1. Matrix Addition
2. Matrix Subtraction
3. Scalar Matrix Multiplication
4. Element-wise Matrix Multiplication
5. Matrix Multiplication
6. Matrix Transpose
7. Trace of a Matrix
8. Solve System of Linear Equations
9. Determinant
10. Inverse
11. Eigenvalue and Eigenvector
12. Exit
Exiting the program.


Above Functions are written seperately (To know )

In [21]:
import numpy as np

In [2]:
M = 6
N = 4
arr1 = np.random.randint(1,100,(M,N))
arr1

array([[83, 97, 40, 63],
       [86,  8, 24,  4],
       [76, 38,  3, 31],
       [42, 71, 23, 33],
       [13, 57, 81, 71],
       [67, 61, 11, 76]])

In [3]:
arr2 = np.random.randint(1,100,(M,N))
arr2

array([[33, 64, 88, 12],
       [53, 38, 87, 60],
       [87, 43, 63, 75],
       [12, 25, 62, 96],
       [76, 85, 76,  8],
       [94, 24, 78, 76]])

In [4]:
add = np.add(arr1,arr2)
add

array([[116, 161, 128,  75],
       [139,  46, 111,  64],
       [163,  81,  66, 106],
       [ 54,  96,  85, 129],
       [ 89, 142, 157,  79],
       [161,  85,  89, 152]])

In [5]:
sub = np.subtract(arr1,arr2)
sub

array([[ 50,  33, -48,  51],
       [ 33, -30, -63, -56],
       [-11,  -5, -60, -44],
       [ 30,  46, -39, -63],
       [-63, -28,   5,  63],
       [-27,  37, -67,   0]])

In [9]:
scalar_mult = arr1 * 2
scalar_mult

array([[166, 194,  80, 126],
       [172,  16,  48,   8],
       [152,  76,   6,  62],
       [ 84, 142,  46,  66],
       [ 26, 114, 162, 142],
       [134, 122,  22, 152]])

In [10]:
elementwise = arr1 * arr2
elementwise

array([[2739, 6208, 3520,  756],
       [4558,  304, 2088,  240],
       [6612, 1634,  189, 2325],
       [ 504, 1775, 1426, 3168],
       [ 988, 4845, 6156,  568],
       [6298, 1464,  858, 5776]])

In [11]:
mat_mat_mult = np.dot(arr1,arr2.T)
mat_mat_mult

array([[13223, 15345, 18637, 11949, 18097, 18038],
       [ 5510,  7190,  9638,  3104,  9072, 10452],
       [ 5576,  7593, 10760,  5024,  9482, 10646],
       [ 8350,  8905, 10631,  6873, 11239,  9954],
       [12057, 14162, 14010, 13419, 12557, 14304],
       [ 7995, 11386, 14845, 10307, 11721, 14396]])

In [13]:
print(arr1.T)
print(arr2.T)

[[83 86 76 42 13 67]
 [97  8 38 71 57 61]
 [40 24  3 23 81 11]
 [63  4 31 33 71 76]]
[[33 53 87 12 76 94]
 [64 38 43 25 85 24]
 [88 87 63 62 76 78]
 [12 60 75 96  8 76]]


In [14]:
trace = np.trace(arr1)
trace

127

In [17]:
arr1 = np.random.randint(1,100,(5,5))
arr2 = np.random.randint(1,100,(5,5))

In [24]:
coeff =np.array([[3,2],[4,-1]])
eq = np.array([5,3])

In [25]:
solve = np.linalg.solve(coeff,eq)
solve

array([1., 1.])

In [20]:
determinant = np.linalg.det(arr1)
determinant

455369891.9999999

In [21]:
inverse = np.linalg.inv(arr1)
inverse

array([[-0.02141672,  0.01814625, -0.01863894,  0.01784239,  0.01896874],
       [-0.02046291,  0.00109185,  0.00042366,  0.0005423 ,  0.02518488],
       [ 0.0656232 , -0.01476719,  0.03033237, -0.039314  , -0.06189639],
       [-0.03687163,  0.00746758, -0.01116532,  0.03235373,  0.02485042],
       [ 0.04937472, -0.0169067 ,  0.01467296, -0.02862067, -0.02597444]])

In [22]:
values,vectors = np.linalg.eig(arr1)
print("Values : ",values)
print("Vectors : ",vectors)

Values :  [236.47526475 +0.j          -5.59662561+22.40297268j
  -5.59662561-22.40297268j  59.85899324 +5.32010563j
  59.85899324 -5.32010563j]
Vectors :  [[-0.37640193+0.j         -0.22338472-0.27446439j -0.22338472+0.27446439j
   0.29888479+0.05965139j  0.29888479-0.05965139j]
 [-0.51360401+0.j         -0.28277522+0.29707984j -0.28277522-0.29707984j
  -0.41702277+0.20049668j -0.41702277-0.20049668j]
 [-0.62043255+0.j          0.63967422+0.j          0.63967422-0.j
  -0.58886126+0.j         -0.58886126-0.j        ]
 [-0.29141628+0.j         -0.29476806-0.06471078j -0.29476806+0.06471078j
   0.45204802-0.31733966j  0.45204802+0.31733966j]
 [-0.35308995+0.j          0.43979837+0.11344118j  0.43979837-0.11344118j
  -0.00163118+0.20295459j -0.00163118-0.20295459j]]


In [1]:
import numpy as np

# Function to take matrix input
def input_matrix(rows, cols):
    print(f"Enter the values for a {rows}x{cols} matrix:")
    matrix = []
    for i in range(rows):
        row = list(map(float, input(f"Enter values for row {i + 1} separated by space: ").split()))
        if len(row) != cols:
            raise ValueError("Number of columns entered doesn't match the expected column size.")
        matrix.append(row)
    return np.array(matrix)

# Get dimensions of the matrices
rows = int(input("Enter the number of rows: "))
cols = int(input("Enter the number of columns: "))

# Input matrices
print("Matrix A:")
matrix_a = input_matrix(rows, cols)

print("\nMatrix B:")
matrix_b = input_matrix(rows, cols)

# Perform matrix addition
result = matrix_a + matrix_b

# Display the result
print("\nMatrix A + Matrix B:")
print(result)


Matrix A:
Enter the values for a 2x2 matrix:

Matrix B:
Enter the values for a 2x2 matrix:

Matrix A + Matrix B:
[[4. 4.]
 [6. 5.]]
